### ISSUE TITLE
Vote - should TAC meetings be recorded

### ISSUE THREAD

**Issue by jmertic** [AcademySoftwareFoundation/tac#163]
Please submit your vote for if TAC meetings should be automatically recorded.

+1 - Yes
0 - Abstain
-1 - No

**Comment by slooper** [comment]
-1

**Comment by lgritz** [comment]
-1

**Comment by fpsunflower** [comment]
-1

**Comment by davefellows** [comment]
+1. They've been hard to me to join recently (though Greg Denton will probably stand in for me for now).

**Comment by pilarmolinalopez** [comment]
-1

**Comment by jminor** [comment]
-1

---
Joshua Minor (he-him)
OpenTimelineIO Technical Steering Committee Chairperson
joshm@pixar.com

**Comment by bcipriano** [comment]
+1

**Comment by kdt3rd** [comment]
0 with σ of 1.0. It doesn't seem worth the extra overhead with the amazing notes that JF takes, but I get the desire for those who aren't able to attend, so I'll just go along with the majority

**Comment by mkuhlens** [comment]
+1

**Comment by derekhaase** [comment]
+1

**Comment by wjballew** [comment]
-1 (not a really strong opinion here, but I am concerned that recording the meetings my hinder some discussion)

**Comment by ssteinbach** [comment]
-1.  I'd rather have the written notes that are easy to scan.

**Comment by jfpanisset** [comment]
0

Plusses and minuses, there's no plan to stop doing written notes, although
in theory if you upload video to YouTube you can get pretty good automatic
transcription.

JF

**Comment by michdolan** [comment]
-1

**Comment by kmuseth** [comment]
0

I'm on the fence - could go either way, but I'd rate written summaries higher

**Comment by soldotna** [comment]
-1 agree that the written notes have been good (thanks JF), and if there's a need for video recordings, could be convinced otherwise in the future.

**Comment by comand** [comment]
-1 -- I would also agree that the more concise written notes are more useful for me than trying to listen through the whole hour in a recording.

**Comment by cary-ilm** [comment]
-0.5. I like the written notes, and I generally think that recording can have a stifling effect on discussions.

**Comment by meshula** [comment]
-1, notes are fantastic, as others have mentioned recording likely restricts free conversation

**Comment by ee33** [comment]
-1

**Comment by dheckenberg** [comment]
0

I agree with comments on both sides but don't have a strong personal position.

**Comment by jmertic** [comment]
It appears that -1's have it, so I will disable the automatic recording of TAC meetings going forward. Thank you all!

**Comment by lgritz** [comment]
Must individual projects repeat this formal voting process, or can TSC chairs use this as their default, unless their members seem to want recording?

**Comment by jmertic** [comment]
@lgritz I'm not reading this as a mandate for hosted projects, so each project has the liberty to decide what they do best for their community. @dheckenberg Let me know if I interpreted the TAC's intentions correctly.
