### ISSUE TITLE
Update CLA guidance and sample CLA

### ISSUE THREAD

**Issue by jfpanisset** [AcademySoftwareFoundation/tac#184]
As discussed on TAC meeting of 29-Jul-2020, @jmertic could you update the sample CLA and guidance to reflect the preference for the Apache CLA going forward?

**Comment by jmertic** [comment]
I've created a PR ( #186 ) in draft for @swinslow to review before I bring to the TAC.

**Comment by dheckenberg** [comment]
I'll add a follow up item for the upcoming TAC meeting.
