### ISSUE TITLE
Annual Review - Open Shading Language

### ISSUE THREAD

**Issue by jmertic** [AcademySoftwareFoundation/tac#437]

**Comment by jmertic** [comment]
Presentation: https://docs.google.com/presentation/d/1AYqh62o0dxU2vot7LS7upa_FDfrDB3rl-0LUplT5xLE/edit?usp=sharing

**Comment by jmertic** [comment]
@yarille - can you update the review dates and move to Adopted Stage on the landscape and PCC?

**Comment by jmertic** [comment]
Update - reviewing this with OSL to ensure all requirements have been met.

**Comment by jmertic** [comment]
@fpsunflower @lgritz Confirming if OSL is ready for it's annual review on Wednesday, Oct 2 - let myself and @yarille know.

**Comment by lgritz** [comment]
I'm not ready at all!

Dev Days, imminent annual releases of both OSL and OIIO, and preparing SPI's Scitech applications for the year (as well as serving on the committee myself) have really made the last few weeks crazy.

**Comment by yarille** [comment]
renewed via TAC vote on 10/30
