### ISSUE TITLE
Dev Days Recap

### ISSUE THREAD

**Issue by carolalynn22** [AcademySoftwareFoundation/tac#476]
Site/Registration is live: https://sites.google.com/view/aswfdevdays/home

Project Lead info / tasks: https://docs.google.com/document/d/1l6VTBRXZju4twJKW-PL_oymWEJTD1I3I7BtH4GY-KLk/edit?usp=sharing

Example Outreach Templates: https://docs.google.com/document/d/17zDTKW39wWHzN-NNZjzyy98BgYMxhFC38AOykWW2u5k/edit?usp=sharing

**Comment by jmertic** [comment]
Final report below.

[Dev Days 2023 Report.pdf](https://github.com/AcademySoftwareFoundation/tac/files/13046476/Dev.Days.2023.Report.pdf)
