### ISSUE TITLE
nanoColor Working Group Charter Proposal

### ISSUE THREAD

**Issue by carolalynn22** [AcademySoftwareFoundation/tac#612]
### Please share any additional details on this topic

OCIO, USD, and MaterialX leaders have been working on a proposal for a lightweight version of OCIO for use in rendering, texture, and material use cases. We are at the point where we would like to discuss and get feedback from the TAC. Here is the charter: https://docs.google.com/document/d/1eGLtOHY-hNKXdtBUJWQHK25WQcK2zjDJYkldmE6eZVY/edit?usp=sharing

### Detail what actions or feedback you would like from the TAC

We are seeking feedback from the TAC on the overall plan, and also for stakeholders to participate from member companies as needed.

### How much time do you need for this topic?

5 minutes or less

**Comment by jmertic** [comment]
Group is forming under OCIO - please engage there if interested.
