### ISSUE TITLE
Starting a Zero Trust Security Working Group

### ISSUE THREAD

**Issue by j-helman** [AcademySoftwareFoundation/tac#620]
### Please share any additional details on this topic

We have a proposal for a Zero Trust Working Group including participation commitments from several ASWF members. We want to update the TAC on the proposal so they can review it for subsequent approval. 

Not sure of the process here. We could do 5-10 minutes at one meeting, get TAC review and comments off line, and then bring back for approval. 

### Detail what actions or feedback you would like from the TAC

TAC feedback on the proposed charter and subsequent TAC approval.

### How much time do you need for this topic?

5 minutes or less

**Comment by jmertic** [comment]
Thanks @j-helman - we should be able to accommodate this today. Looking forward to the update!

**Comment by j-helman** [comment]
Great. I'd like Daryll Strauss to join the call as well. Any special arrangements for that?

**Comment by jmertic** [comment]
None at all - have him go to https://zoom-lfx.platform.linuxfoundation.org/meeting/97880950229?password=81d2940e-c055-43b9-9b5a-6cd7d7090feb to get an invite and join the meeting

**Comment by j-helman** [comment]
Also, should I upload the proposed charter now to [https://github.com/AcademySoftwareFoundation/tac/issues/new/choose](https://github.com/AcademySoftwareFoundation/tac/issues/new/)choose, or wait until after the meeting discussion?

**Comment by jmertic** [comment]
Go ahead and upload it now as it will be helpful as a pre-read

**Comment by jmertic** [comment]
@j-helman will follow up with details on operations.
