### ISSUE TITLE
Follow-up discussion on New Project Proposal - Pillow

### ISSUE THREAD

**Issue by aclark4life** [AcademySoftwareFoundation/tac#631]
### Project description

The Python Imaging Library adds image processing capabilities to your Python interpreter. This library provides extensive file format support, an efficient internal representation, and fairly powerful image processing capabilities. The core image library is designed for fast access to data stored in a few basic pixel formats. It should provide a solid foundation for a general image processing tool.

### Sponsor from TAC

N/A

### Proposed Project Stage

Adopted

### Please explain how this project is aligned with the mission of the Academy Software Foundation?

To explain this I'll cite this [blog entry](https://www.aswf.io/news/aswf-deep-dive-openexr-origin-story-part-3/), in which Cary Phillips said:

> "Before the ASWF was established, the responsibility for fixing bugs and addressing security issues was resting solely on ILM. Now that responsibility is shouldered by people throughout the industry which is a much better position to be in."

Currently a 4-person team funded by Tidelift is responsible for fixing Pillow bugs and addressing security issues. The current funding is insufficient and so therefore the long term viability of Pillow has not been secured. Insomuch as the ASWF cares about the entire VFX Reference Platform, even small projects, our missions are aligned! **EDIT: this request is not exclusively about $$$, although $$$ would help. It's more about trying to get folks to care about and appreciate Pillow's role in the ecosystem.** 🙏 

### What is the project’s license for code contributions and methodology for code contributions?

[HPND](https://github.com/python-pillow/Pillow/blob/main/LICENSE)

### What tool or platform is utilized for source control (GitHub, etc.), and what is the location (e.g., URL)?

https://github.com/python-pillow/Pillow

### What are the external dependencies of the project, and what are the licenses of those dependencies?

-  libjpeg: The Independent JPEG Group's JPEG software. License: Independent JPEG Group's JPEG license (compatible with the GNU GPL).
-  zlib: A general-purpose data compression library. License: Zlib License (compatible with the GNU GPL).
-  freetype: A software library to render fonts. License: FreeType License (similar to the GNU GPL).
-  lcms2: Little CMS (Color Management System) version 2. License: MIT License.
-  libtiff: A library for reading and writing TIFF (Tagged Image File Format) files. License: libtiff License (compatible with the GNU GPL).
-  webp: A method for lossy and lossless compression of images developed by Google. License: Apache License 2.0.

    

### What roles does the project have (e.g., maintainers, committers?) Who are the current core committers of the project, or which can a list of committers be found?

The core team includes [myself](https://github.com/aclark4life) (fork author and project leader), [Eric Soroos](https://github.com/wiredfool), [Hugo van Kemenade](https://github.com/hugovk),  [Andrew Murray](https://github.com/radarhere). In addition to the core team we have [~400 other contributors](https://github.com/python-pillow/Pillow/contributors).

   

### What mailing lists are currently used by the project?

[ Image-sig ](https://www.python.org/community/sigs/current/image-sig/) back in the day, but now-a-days [GitHub Discussions](https://github.com/python-pillow/Pillow/discussions)

### What tool or platform is leveraged by the project for issue tracking?

https://github.com/python-pillow/Pillow/issues

### Does the project have an OpenSSF Best Practices Badge? Do you foresee any challenges in obtaining one?

[Yes](https://www.bestpractices.dev/en/projects/6331)

### What is the project’s website? Is there a wiki?

- https://python-pillow.org
- https://pillow.readthedocs.io/en/stable

### What social media accounts are used by the project?

We're retiring our [Twitter](https://twitter.com/PythonPillow) and moving to [Mastodon](https://fosstodon.org/@pillow).

### What is the project’s release methodology and cadence?

[Quarterly releases, at least one of which is timed to occur immediately following annual major Python releases.](https://pillow.readthedocs.io/en/stable/releasenotes/index.html#)

### Are any trademarks, registered or unregistered, leveraged by the project? Have any trademark registrations been filed by the project or any third party anywhere in the world?

No, unless you count the [Python trademark](https://www.python.org/psf/trademarks/).

**Comment by jmertic** [comment]
@aclark4life - please confirm if you can present at the TAC meeting on Wednesday ( 3/20 ).

**Comment by aclark4life** [comment]
> @aclark4life - please confirm if you can present at the TAC meeting on Wednesday ( 3/20 ).

Can do! Although I don't have any meeting details yet. I am on EDT. Thanks

**Comment by jmertic** [comment]
Meeting info is at https://tac.aswf.io/meetings/#meetings

**Comment by aclark4life** [comment]
Cool so 4:00PM EDT, see you then.

**Comment by aclark4life** [comment]
Hey folks no PDF or PPT yet but you can check out my Reveal.js presentation if you are interested, see you in a few: https://github.com/python-pillow/pillow-aswf

**Comment by aclark4life** [comment]
Thanks for the meeting, folks! 

One obvious counterpoint to @carolalynn22 's comment about OpenImageIO's overlapping feature set would be that if OIIO was the go to for every image processing need in VFX pipelines then Pillow would not be there at all. 

It's there perhaps because it's much "lighter" than OpenImageIO most notably in that OpenImageIO is VFX-specific whereas Pillow is not. Additionally, I wonder if the argument that once OIIO wheels are ubiquitous then Pillow usage will drop. I don't know enough about VFX to guess about that but seems like a possibility. 🤷 

That said, I already agree with @carolalynn22 's point about alignment and, given that Pillow is not VFX software, you can make a very strong argument that Pillow is _not_ in alignment with the ASWF and therefore should not be supported, by the ASWF at least. Other LF umbrellas may apply.

**Comment by aclark4life** [comment]
[PDF](https://github.com/python-pillow/pillow-aswf/blob/main/pillow-aswf.pdf)

**Comment by jmertic** [comment]
Hi @aclark4life - the TAC discussed this today and was wondering if you saw alignment with other ASWF projects and/or if there was an ASWF member who would be willing to support this work with resources. Let us know your thoughts.

One possibility could be to bring the project into the LF as an unfunded project if you are looking for a neutral home for collaboration. Happy to discuss that further if it is of interest.

**Comment by aclark4life** [comment]
Thank you @jmertic and TAC, will discuss with @python-pillow team.

The only alignment I see is with @lgritz and OIIO, but I wouldn't ask for any resources in that case. Right now I'm interested in writing enough C (or finding someone to help me write enough C) to satisfy this long-standing Pillow issue and make Pillow more useful for GIS, VFX and ML industries, as described [here](https://github.com/python-pillow/Pillow/issues/1888#issuecomment-2057950781), [here](https://github.com/python-pillow/Pillow/issues/1888#issuecomment-2057966033) and [here](https://github.com/python-pillow/Pillow/issues/1888#issuecomment-2061863380).

If being an unfunded LF project helps with that, then maybe. I think it's fair to say that I'd like to raise awareness about Pillow's development process and I definitely appreciate the suggestion. If you'd be willing to meet again to discuss further, let me know. Thank you again @jmertic and TAC, I appreciate all of your time and consideration.

**Comment by jmertic** [comment]
Hi @aclark4life - if you want to pursue the unfunded LF project route, please email me at jmertic at linuxfoundation dot org and I can connect you with the formation team on next steps.

Closing this one for now.
