### ISSUE TITLE
Do we need the JIRA instance anymore?

### ISSUE THREAD

**Issue by jmertic** [AcademySoftwareFoundation/tac#639]
### Please share any additional details on this topic

@tykeal was doing some maintainence on the ASWF JIRA instance, and noticed there hasn't been activity for some time.

### Detail what actions or feedback you would like from the TAC

Determine if this resource is needed anymore.

### How much time do you need for this topic?

5 minutes or less

**Comment by tykeal** [comment]
I'll add to that. From what I can tell, the Jira has never actually been used! Confluence is used semi-regularly, but not Jira.

**Comment by jfpanisset** [comment]
Gut feeling is that projects prefer using GitHub Issues which are more readily discoverable and better integrated with GitHub centric dev process, and may not require full power / complexity of JIRA project management tools?

If it isn't used, I personally say we should take it down.

**Comment by cary-ilm** [comment]
We have no interest in using Jira with OpenEXR. Our team is not big enough and development is not active enough to need anything more than GitHub Issues

We use Confluence for TSC meeting notes (avoids polluting the source repo), and a few other things with very low traffic like project ideas.

**Comment by jmertic** [comment]
@yarille Can you do a vote on this with the TAC via email?

**Comment by tykeal** [comment]
Did this vote ever finish?

**Comment by yarille** [comment]
@tykeal we still need a couple votes for a quorum. I will send a reminder.

**Comment by yarille** [comment]
Approved by TAC vote on 5/22.

**Comment by tykeal** [comment]
@yarille approved for removal?
