### ISSUE TITLE
Volunteer for SLP 2024!

### ISSUE THREAD

**Issue by carolalynn** [AcademySoftwareFoundation/tac#645]
Please sign up to volunteer for SLP 2024 - and also send the info out to your companies! https://docs.google.com/forms/d/e/1FAIpQLSfVt4IDJNvdObrOTG3fULwcezkRUFrXNvSdDSNtC6pA3pNIkw/viewform

Long Description:
We have some really great applications coming in for the Summer Learning Program (SLP), organized by our D&I Working Group, and now we need your help!! The SLP runs from June 16 - August 9. We have different levels of involvement depending on your bandwidth.

We are looking for:
- Mentors (~8 hours): paired 1:1 with an SLP and meet weekly for 30-60 minutes
- Guest Mentors (~1 hour + prep time): fill in for a mentor session if a mentor is on vacation
- Team Leads (~12 hours): lead a small group of 4-5 learners and help them set and meet goals
- Speakers (~1 hour + prep time): present on a topic (your career or journey, speak on a panel about a specified topic, or share ideas in your field that are accessible to 18 year old/entry level individuals)
- Application Reviewers (~3 hours): review and assess applicants

**Comment by jmertic** [comment]
@carolalynn - let us know if this should stay on the agenda as an update for the next TAC meeting or not. Thanks!

**Comment by carolalynn** [comment]
I think it should stay on for one more, and then we can close it out.

**Comment by jmertic** [comment]
Works for me - thanks for the quick response!
