### ISSUE TITLE
Dev Days 2024

### ISSUE THREAD

**Issue by carolalynn** [AcademySoftwareFoundation/tac#662]
Dev Days 2024 is scheduled for Sept 25-26, 2024. More details on the event are at https://www.aswf.io/dev-days-2024/.

The general timeline for the event is as follows.

- Applications for projects to participate closes on June 15th, 2024. Projects can apply to participate [here](https://github.com/AcademySoftwareFoundation/tac/issues/new/choose).
- Participants can begin applying to be a part of Dev Days starting July 15th through September 15th. The participant application form will be available at https://www.aswf.io/dev-days-2024/.

Other resources:

- [Participant Guidelines](https://wiki.aswf.io/display/DEVDAYS/Participant+Guidelines)
- [Project Guidelines](https://wiki.aswf.io/display/DEVDAYS/Project+Guidelines)

**Comment by jmertic** [comment]
Update for May 15th, 2024:

- The project application form is now [live](https://wiki.aswf.io/display/DEVDAYS/Project+Guidelines)!

**Comment by jmertic** [comment]
Update for July 11th, 2024:

- 6 projects committed to participating - https://github.com/AcademySoftwareFoundation/tac/issues?q=is%3Aissue+is%3Aopen+label%3A%22dev+days%2F2024%22
- Reg form and updated website to launch in the next week - https://www.aswf.io/dev-days-2024/

**Comment by carolalynn** [comment]
Mention office hours:

Session One – September 9 at 4:00 pm PT: Picking a project, CLAs, and general participation questions. [Meeting Link](https://zoom-lfx.platform.linuxfoundation.org/meeting/91859275895?password=182262a0-1dc6-4d2f-aebc-8040f688add6&__hstc=120031703.d3d8844a9a63e1740e642bef2af23f79.1721407454911.1724964087369.1725397939622.7&__hssc=120031703.1.1725397939622&__hsfp=1260979542).
Session Two – September 16 at 10:00 am PT: Picking an issue and GitHub related questions. [Meeting Link](https://zoom-lfx.platform.linuxfoundation.org/meeting/93805107077?password=8a4d64a5-0a48-41a8-a9a4-82b46fafea5d&__hstc=120031703.d3d8844a9a63e1740e642bef2af23f79.1721407454911.1724964087369.1725397939622.7&__hssc=120031703.1.1725397939622&__hsfp=1260979542).
Session Three – September 23 at 4:00 pm PT: CMake and build environments. [Meeting Link](https://zoom-lfx.platform.linuxfoundation.org/meeting/91790174616?password=6729d6d1-437d-4da3-a152-616f0e01b18b&__hstc=120031703.d3d8844a9a63e1740e642bef2af23f79.1721407454911.1724964087369.1725397939622.7&__hssc=120031703.1.1725397939622&__hsfp=1260979542).

**Comment by jmertic** [comment]
Great work! Here is the latest numbers on PRs.... ![Image](https://github.com/user-attachments/assets/71ca83a8-0e49-46f7-8e9c-f3ec8ee6998f)
