### ISSUE TITLE
Clarify policy on incorporating Zoom chat to TAC meeting notes

### ISSUE THREAD

**Issue by jfpanisset** [AcademySoftwareFoundation/tac#667]
### Please share any additional details on this topic

 I've been trying to capture the contents of the Zoom chat and add to meeting notes since there's a lot of relevant side discussion happening there, but I realize that not everyone might be aware of that, or cool with it. So would be good to make it explicit whether we want this or not, and remind participants at the start of a meeting whether chat will show up or not in meeting notes.
 
Would also be good to figure out if LFX platform captures zoom chat, currently zoom recordings are disabled for TAC meetings.

### Detail what actions or feedback you would like from the TAC

A quick vote on whether Zoom chat is to be incorporated into TAC meeting notes, or considered ephemeral.

### How much time do you need for this topic?

None

**Comment by ee33** [comment]
I feel that participants should have a backspace key: They should be able to clarify or even redact their own remarks made during live meetings. This should be rare but possible. That's (part of) why text meeting notes are so much better than video.

Thus: Capturing the chat log sounds great, as long as it is editable.

**Comment by jmertic** [comment]
@ee33 While I do agree, since we use GitHub, there really isn't a perfect way to redact previous meeting notes like that. Corrections and clarifications are quite doable. 

The other option is do have a review peroid for participants to make comments/corrections to notes before they are committed.

**Comment by jfpanisset** [comment]
Currently my workflow is the following:

- create the meeting template in hackmd.io based on the auto generated template in the TAC GitHub repo
- take live nmodes in hackmd.io
- do some corrections in hackmd.io
- download markdown locally
- edit in VS Code, taking advantage of better editing capabilities and Markdown "linting"
- commit and push to TAC repo
- this autogenerates the Netlify version at tac.aswf.io

Usually I merge the chat comments in VS Code, and try to have the meeting notes up as soon as possible, usually within an hour or two, but once in a while that might slip by a day or two.

I'm happy to add a "cool off period" before notes get committed to GitHub where indeed they become mostly immutable (even if edited after the fact). I can commit to merging the chat comments in Hackmd so they are globally visible (I post a link to Hackmd in Slack before the meeting), and announcing in the #tac Slack channel "if anyone wants to amend what I've recorded, please DM me in the next 6 hours / edit yourself in hackmd.io", and commit to GitHub the next morning?
