### ISSUE TITLE
GPU support on CI runners

### ISSUE THREAD

**Issue by kmuseth** [AcademySoftwareFoundation/tac#675]
### Please share any additional details on this topic

need for OpenVDB CI

### Detail what actions or feedback you would like from the TAC

approval

### How much time do you need for this topic?

5 minutes or less

**Comment by jmertic** [comment]
@jfpanisset @tykeal - wondering if the CI Working Group should look at this first? LMK

**Comment by jmertic** [comment]
@kmuseth to follow up with CI WG on getting this setup
