### ISSUE TITLE
Establish a slack channel for SPK

### ISSUE THREAD

**Issue by rydrman** [AcademySoftwareFoundation/tac#780]
### Please share any additional details on this topic

We announced and opened the SPK project at DigiPro this year - although we haven't considered whether this project could one day be an ASWF project, we are looking for an accessible place where the community can connect with us and discuss the project.

We have our own Slack instance already, but it is hard to find and I believe that everyone would prefer not to have yet another Slack instance for one specific topic.

https://spkenv.dev

### Detail what actions or feedback you would like from the TAC

Consider adding a slack channel for spk to the ASWF slack instance

### How much time do you need for this topic?

5 minutes or less

**Comment by jmertic** [comment]
Action is to see if other ASWF members see value in having the channel in the ASWF Slack; revisit in the next month or so.

**Comment by rydrman** [comment]
Closing in favour of #915
