### ISSUE TITLE
Open Review Initiative Annual Project Review

### ISSUE THREAD

**Issue by erikstrauss** [AcademySoftwareFoundation/tac#809]
### Please share any additional details on this topic

[Slide Deck for Discussion](https://docs.google.com/presentation/d/1aC-PXOWwoCJ45gPSejx59RO3FBugs_6L/edit#slide=id.p1)

### Detail what actions or feedback you would like from the TAC

Moving ORI from Sandbox to Incubation

### How much time do you need for this topic?

At least 30 minutes

**Comment by jmertic** [comment]
Merging into existing issue #436
