### ISSUE TITLE
Proposal to vote on MaterialX becoming an Adopted member

### ISSUE THREAD

**Issue by jstone-lucasfilm** [AcademySoftwareFoundation/tac#840]
### Please share any additional details on this topic

After recent work on our build process, release process, and documentation, we believe the MaterialX project now meets all of the OpenSSF requirements for an Adopted project of the ASWF:

https://www.bestpractices.dev/en/projects/6025

### Detail what actions or feedback you would like from the TAC

Would the timing be right to hold a TAC vote on including MaterialX as an Adopted project?

### How much time do you need for this topic?

5 minutes or less

**Comment by yarille** [comment]
Approved via LFX Vote 9/23
