### ISSUE TITLE
upgrade GPUs of CI runners

### ISSUE THREAD

**Issue by kmuseth** [AcademySoftwareFoundation/tac#863]
### Please share any additional details on this topic

fVDB (an ML extension to PyTorch) has recently been added to OpenVDB. The CI of fVDB needs newer Nvidia GPUs than what's currently available.

### Detail what actions or feedback you would like from the TAC

Hear if other ASWF projects has simular needs to OpenVDB, and start a discussion about how we can upgrade the existing GPUs on the CI runners. One option is for Nvidia to help, in which case we need to identify someone on the TAC that NVIDIA can work with.

### How much time do you need for this topic?

5 minutes or less

**Comment by jmertic** [comment]
@tykeal Not sure if you have any insight on this?

**Comment by tykeal** [comment]
@jmertic the only insight I currently have on this is that the available GPU runners from GitHub do not currently meet the need of OpenVDB as they are too old a generation. I've got a query into GitHub about when we might see newer GPUs

**Comment by jfpanisset** [comment]
See discussion in #wg-ci: the "small" GPU config for AWS CodeBuild offers a NVIDIA A10G GPU with support for INT8 and TF32 data formats required for the GPU test code in OpenVDB:

https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectEnvironment.html

LF releng ticket has been created to start the process of setting up OpenVDB to use CodeBuild like OCIO does so they can have access to that GPU.
