### ISSUE TITLE
TAC Chair / Vice Chair for 2025

### ISSUE THREAD

**Issue by jmertic** [AcademySoftwareFoundation/tac#913]
Per the [TAC Roles](https://tac.aswf.io/process/tac_roles.html), Larry Gritz will move from the TAC Vice Chair role to the TAC Chair role, effective 1/1/25 through 12/31/25.

Carol Payne has come forward with interest in serving in the TAC Vice Chair role, effective 1/1/25 through 12/31/25.

We thank Kimball Thurston for all his leadership in the TAC for the past several year.

**TAC ACTION: Approve Larry Gritz as TAC Chair and Carol Payne as TAC Vice Chair for 2025.**

**Comment by yarille** [comment]
Approved via LFX vote - 12/16
